[project]
name = "netbox-checker"
version = "0.1.0"
description = "Simple tool to check the status of a NetBox instance"
requires-python = ">=3.8"
dependencies = [
    "requests",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
